# Student Performance Prediction

In [136]:
import pandas as pd

In [137]:
data=pd.read_csv("student_habits_performance.csv")

In [138]:
data.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [139]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   str
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   str
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   str
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   str
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    str
 12  internet_quality               1000 non-null   str
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   str
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), str(7)
memory usage: 125.1 KB

In [140]:
data.isna().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [141]:
data.duplicated().sum()

np.int64(0)

In [142]:
data.shape

(1000, 16)

In [143]:
data.select_dtypes(float)

,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exam_score
0,0.0,1.2,1.1,85.0,8.0,56.2
1,6.9,2.8,2.3,97.3,4.6,100.0
2,1.4,3.1,1.3,94.8,8.0,34.3
3,1.0,3.9,1.0,71.0,9.2,26.8
4,5.0,4.4,0.5,90.9,4.9,66.4
...,...,...,...,...,...,...
995,2.6,0.5,1.6,77.0,7.5,76.1
996,2.9,1.0,2.4,86.0,6.8,65.9
997,3.0,2.6,1.3,61.9,6.5,64.4
998,5.4,4.1,1.1,100.0,7.6,69.7
999,4.3,2.9,1.9,89.4,7.1,74.9

In [144]:
data.select_dtypes(object)

/var/folders/0h/11z4dqc548nccfbdkpdc8phr0000gn/T/ipykernel_728/4181833553.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.select_dtypes(object)

,student_id,gender,part_time_job,diet_quality,parental_education_level,internet_quality,extracurricular_participation
0,S1000,Female,No,Fair,Master,Average,Yes
1,S1001,Female,No,Good,High School,Average,No
2,S1002,Male,No,Poor,High School,Poor,No
3,S1003,Female,No,Poor,Master,Good,Yes
4,S1004,Female,No,Fair,Master,Good,No
...,...,...,...,...,...,...,...
995,S1995,Female,No,Fair,High School,Good,Yes
996,S1996,Female,Yes,Poor,High School,Average,Yes
997,S1997,Male,No,Good,Bachelor,Good,Yes
998,S1998,Male,Yes,Fair,Bachelor,Average,No
999,S1999,Female,No,Good,Bachelor,Average,No

In [145]:
data.gender.value_counts()

gender
Female    481
Male      477
Other      42
Name: count, dtype: int64

In [146]:
data['gender'] = data['gender'].map({"Male": 1, "Female": 0, "Other": 2})

In [147]:
data

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,0,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,0,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,1,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,0,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,0,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,0,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,0,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,1,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,1,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,0,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [148]:
data.part_time_job.value_counts()

part_time_job
No     785
Yes    215
Name: count, dtype: int64

In [149]:
data['part_time_job'] = data['part_time_job'].map({"Yes": 1, "No": 0})

In [150]:
data

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,0,0.0,1.2,1.1,0,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,0,6.9,2.8,2.3,0,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,1,1.4,3.1,1.3,0,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,0,1.0,3.9,1.0,0,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,0,5.0,4.4,0.5,0,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,0,2.6,0.5,1.6,0,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,0,2.9,1.0,2.4,1,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,1,3.0,2.6,1.3,0,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,1,5.4,4.1,1.1,1,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,0,4.3,2.9,1.9,0,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [151]:
data['extracurricular_participation'] = data['extracurricular_participation'].map({"Yes": 1, "No": 0})

In [152]:
data

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,0,0.0,1.2,1.1,0,85.0,8.0,Fair,6,Master,Average,8,1,56.2
1,S1001,20,0,6.9,2.8,2.3,0,97.3,4.6,Good,6,High School,Average,8,0,100.0
2,S1002,21,1,1.4,3.1,1.3,0,94.8,8.0,Poor,1,High School,Poor,1,0,34.3
3,S1003,23,0,1.0,3.9,1.0,0,71.0,9.2,Poor,4,Master,Good,1,1,26.8
4,S1004,19,0,5.0,4.4,0.5,0,90.9,4.9,Fair,3,Master,Good,1,0,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,0,2.6,0.5,1.6,0,77.0,7.5,Fair,2,High School,Good,6,1,76.1
996,S1996,17,0,2.9,1.0,2.4,1,86.0,6.8,Poor,1,High School,Average,6,1,65.9
997,S1997,20,1,3.0,2.6,1.3,0,61.9,6.5,Good,5,Bachelor,Good,9,1,64.4
998,S1998,24,1,5.4,4.1,1.1,1,100.0,7.6,Fair,0,Bachelor,Average,1,0,69.7
999,S1999,19,0,4.3,2.9,1.9,0,89.4,7.1,Good,2,Bachelor,Average,8,0,74.9

In [153]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   str
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   int64
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   int64
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   str
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    str
 12  internet_quality               1000 non-null   str
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   int64
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(6), str(4)
memory usage: 125.1 KB

In [154]:
data.drop('student_id', axis=1, inplace=True)

In [156]:
data.drop('diet_quality', axis=1, inplace =True)

In [157]:
data.drop('parental_education_level', axis=1, inplace =True)

In [158]:
data.drop('internet_quality', axis=1, inplace=True)

In [159]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            1000 non-null   int64
 1   gender                         1000 non-null   int64
 2   study_hours_per_day            1000 non-null   float64
 3   social_media_hours             1000 non-null   float64
 4   netflix_hours                  1000 non-null   float64
 5   part_time_job                  1000 non-null   int64
 6   attendance_percentage          1000 non-null   float64
 7   sleep_hours                    1000 non-null   float64
 8   exercise_frequency             1000 non-null   int64
 9   mental_health_rating           1000 non-null   int64
 10  extracurricular_participation  1000 non-null   int64
 11  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(6)
memory usage: 93.9 KB

In [360]:
X = data.drop("exam_score",axis = 1)
y = data.exam_score

In [361]:
from sklearn.model_selection import train_test_split

In [362]:
X_train,X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=42)

In [363]:
X_train.shape

(700, 11)

In [364]:
y_train.shape

(700,)

In [365]:
X_test.shape

(300, 11)

In [366]:
y_test.shape

(300,)

In [367]:
from sklearn.linear_model import LinearRegression

In [368]:
lr = LinearRegression()

In [369]:
lr.fit(X_train,y_train)

LinearRegression()

In [370]:
lr.score(X_train,y_train)

0.9011302533964725

In [371]:
y_train_pred = lr.predict(X_train)

In [372]:
from sklearn.metrics import r2_score, mean_absolute_error

In [373]:
r2_score(y_train,y_train_pred)

0.9011302533964725

In [374]:
mean_absolute_error(y_train,y_train_pred)

4.2234530257242335

In [375]:
y_pred_test= lr.predict(X_test)

In [376]:
r2_score(y_test,y_pred_test)

0.8982866800262013

In [377]:
mean_absolute_error(y_test, y_pred_test)

4.221950755709954

In [378]:
lr.coef_

array([ 6.72082925e-02,  3.07383471e-01,  9.59213114e+00, -2.74806215e+00,
       -2.36871051e+00,  5.88456661e-03,  1.46780149e-01,  2.02130664e+00,
        1.27415984e+00,  1.94293915e+00, -1.15411164e-01])

In [379]:
lr.intercept_

np.float64(5.532495176563984)

In [380]:
import numpy as np

In [381]:
from sklearn import metrics

In [382]:
ms=metrics.mean_squared_error(y_test, y_pred_test)
print(ms)

28.25203682171958

In [383]:
np.sqrt(ms)

np.float64(5.315264510983398)

In [180]:
from sklearn.linear_model import LassoCV, Lasso

In [181]:
lasso=LassoCV(alphas=[1.0,0.01,0.1,0.12,0.90])

In [182]:
lasso.fit(X_train,y_train)

LassoCV(alphas=[1.0, 0.01, 0.1, 0.12, 0.9])

In [183]:
lasso.alpha_

np.float64(0.1)

In [184]:
lasoo_y_train_pred=lasso.predict(X_train)

In [185]:
r2_score(y_train,lasoo_y_train_pred)

0.9009125035112426

In [186]:
from sklearn.linear_model import RidgeCV

In [187]:
ridgelasso=RidgeCV()

In [188]:
ridgelasso.fit(X_train,y_train)

RidgeCV()

In [189]:
ridgelasso.alpha_

10.0

In [190]:
ridge_y_train_pred=ridgelasso.predict(X_train)

In [191]:
r2_score(y_train,ridge_y_train_pred)

0.9010897145989892

In [202]:
def predict_student_score(age, gender, study, social, netflix, part_time_job, attendance, sleep, exercise, mental_health, extracurricular_participation):
    input_data = {
        'age': [age],
        'study_hours_per_day': [study],
        'social_media_hours': [social],
        'netflix_hours': [netflix],
        'attendance_percentage': [attendance],
        'sleep_hours': [sleep],
        'exercise_frequency': [exercise],
        'mental_health_rating': [mental_health],
        'gender': [gender],                                         # 0: Female, 1: Male, 2: Other
        'part_time_job': [part_time_job],                           # 0: No, 1: Yes
        'extracurricular_participation': [extracurricular_participation] # 0: No, 1: Yes
    }
    
    student_df = pd.DataFrame(input_data)

    student_df = student_df[lr.feature_names_in_]
 
    predicted_score = lr.predict(student_df)
    return predicted_score

print("--- Enter Student Details to Predict Exam Score ---")
print("(For Gender: Female=0, Male=1, Other=2 | For Job & Participation: No=0, Yes=1)\n")

user_age = int(input("Enter Age: "))
user_gender = int(input("Enter Gender (0/1/2): "))
user_study = float(input("Enter Study Hours Per Day: "))
user_social = float(input("Enter Social Media Hours: "))
user_netflix = float(input("Enter Netflix Hours: "))
user_job = int(input("Enter Part time Job (0/1): "))
user_attendance = float(input("Enter Attendance Percentage: "))
user_sleep = float(input("Enter Sleep Hours: "))
user_exercise = int(input("Enter Exercise Frequency per week: "))
user_mental = int(input("Enter Mental Health Rating out of 10: "))
user_participation = int(input("Enter Extracurricular Participation (0/1): "))

final_result = predict_student_score(
    age=user_age, 
    gender=user_gender,
    study=user_study, 
    social=user_social, 
    netflix=user_netflix,
    part_time_job=user_job,
    attendance=user_attendance, 
    sleep=user_sleep, 
    exercise=user_exercise, 
    mental_health=user_mental,
    extracurricular_participation=user_participation
)
print(f" Predicted Exam Score: {round(final_result[0], 2)}")

--- Enter Student Details to Predict Exam Score ---
(For Gender: Female=0, Male=1, Other=2 | For Job & Participation: No=0, Yes=1)

 Predicted Exam Score: 89.74